name: Install dependencies

description: "Install project dependencies and cache node_modules"

inputs:
  node-auth-token:
    description: "NODE_AUTH_TOKEN env variable needed for dependency installations"
    required: true
  github-token:
    description: "GITHUB_TOKEN env variable needed for dependency installations"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      shell: bash
      run: npm ci --no-audit
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
