name: Creating the .env file
description: "Prepare env file in order to propagate credentials"
runs:
  using: "composite"
  steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_VITE_ROWS_API_KEY: ${{ secrets.ROWS_API_KEY }}
        envkey_VITE_SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        envkey_VITE_TABLE_ID: ${{ secrets.TABLE_ID }}
        file_name: .env
        fail_on_empty: true
