name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

# Environment variables available to all jobs and steps in this workflow
env:
  CHROME_VERSION: 121.0.6167.85

jobs:
  audit:
    name: Audit dependencies
    runs-on: rows-fe-default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-node

      - name: Audit dependencies
        run: npm audit --production --audit-level=high

  static-analysis:
    name: Static analysis
    runs-on: rows-fe-default
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/install-dependencies
        with:
          node-auth-token: ${{ secrets.NODE_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Linting JS/TS
        run: npm run lint

      - name: Type checking
        run: npm run check-types

  test:
    name: E2E Tests
    runs-on: ubuntu-4-core-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-node

      - uses: ./.github/actions/install-dependencies
        with:
          node-auth-token: ${{ secrets.NODE_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run E2E tests
        run: node node_modules/puppeteer/install.mjs && npm run test:e2e
